# Generated by Django 4.2.6 on 2023-10-25 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectId', models.AutoField(db_column='prjIdpk', primary_key=True, serialize=False)),
                ('projectName', models.CharField(db_column='prjName', max_length=255)),
                ('projectDescription', models.CharField(db_column='prjDescription', max_length=255)),
                ('projectIsActive', models.BooleanField(blank=True, db_column='prjIsActive', default=True)),
                ('projectStartDate', models.DateField(blank=True, db_column='prjStartDate', null=True)),
                ('projectEndDate', models.DateField(blank=True, db_column='prjEndDate', null=True)),
                ('projectCreateDdate', models.DateTimeField(auto_now_add=True, db_column='tkaCreatedDate')),
                ('projectUpdateddate', models.DateTimeField(auto_now=True, db_column='tkaUpdatedDate')),
                ('projectType', models.CharField(blank=True, db_column='prjType', max_length=255, null=True)),
                ('projectStatus', models.CharField(blank=True, db_column='prjStatus', max_length=255, null=True)),
                ('projectTeamId', models.IntegerField(blank=True, db_column='prjTeamIdfk', null=True)),
            ],
            options={
                'db_table': 'tblproject',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('subtaskId', models.AutoField(db_column='stskIdpk', primary_key=True, serialize=False)),
                ('subtaskkTaskId', models.IntegerField(blank=True, db_column='stskTaskIdfk', null=True)),
                ('subtaskName', models.CharField(db_column='stskName', max_length=255)),
                ('subtaskDescription', models.CharField(db_column='stskDescription', max_length=255)),
                ('subtaskCreateDdate', models.DateTimeField(auto_now_add=True, db_column='tkaCreatedDate')),
                ('subtaskUpdateddate', models.DateTimeField(auto_now=True, db_column='tkaUpdatedDate')),
                ('subtaskPriorityId', models.IntegerField(blank=True, db_column='stskPriorityIdfk', null=True)),
                ('subtaskEndDate', models.DateField(blank=True, db_column='stskEndDate', null=True)),
                ('subtaskIsActive', models.BooleanField(blank=True, db_column='stskIsActive', default=True)),
            ],
            options={
                'db_table': 'tblsubtask',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('taskId', models.AutoField(db_column='tskIdpk', primary_key=True, serialize=False)),
                ('taskName', models.CharField(db_column='tskName', max_length=255)),
                ('taskDescription', models.CharField(db_column='tskDescription', max_length=255)),
                ('taskStatusId', models.IntegerField(blank=True, db_column='statusId', null=True)),
                ('taskCreateDdate', models.DateTimeField(auto_now_add=True, db_column='tkaCreatedDate')),
                ('taskUpdateddate', models.DateTimeField(auto_now=True, db_column='tkaUpdatedDate')),
                ('taskPriorityId', models.IntegerField(blank=True, db_column='tskPriorityIdfk', null=True)),
                ('taskStartDate', models.DateField(blank=True, db_column='startDate', null=True)),
                ('taskEndDate', models.DateField(blank=True, db_column='tskEndDate', null=True)),
                ('taskIsActive', models.BooleanField(blank=True, db_column='tskIsActive', null=True)),
            ],
            options={
                'db_table': 'tbltask',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TaskPriority',
            fields=[
                ('priorityId', models.AutoField(db_column='prIdpk', primary_key=True, serialize=False)),
                ('priorityName', models.CharField(db_column='prName', max_length=255)),
                ('priorityDescription', models.CharField(db_column='prDescription', max_length=255)),
                ('priorityCreateDdate', models.DateTimeField(auto_now_add=True, db_column='tkaCreatedDate')),
                ('priorityUpdateddate', models.DateTimeField(auto_now=True, db_column='tkaUpdatedDate')),
                ('priorityIsActive', models.BooleanField(blank=True, db_column='prIsActive', null=True)),
            ],
            options={
                'db_table': 'tblpriority',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('statusIdp', models.AutoField(db_column='stIdpk', primary_key=True, serialize=False)),
                ('statusName', models.CharField(db_column='stName', max_length=255)),
                ('statusDescription', models.CharField(db_column='stDescription', max_length=255)),
                ('statusCreateDdate', models.DateTimeField(auto_now_add=True, db_column='tkaCreatedDate')),
                ('statusUpdateddate', models.DateTimeField(auto_now=True, db_column='tkaUpdatedDate')),
                ('statusIsActive', models.BooleanField(blank=True, db_column='stIsActive', default=True)),
            ],
            options={
                'db_table': 'tbltaskstatus',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamIdpk', models.AutoField(db_column='tmIdpk', primary_key=True, serialize=False)),
                ('teamName', models.CharField(db_column='tmName', max_length=255)),
                ('teamDescription', models.CharField(db_column='tmDescription', max_length=255)),
                ('teamCreatedDate', models.DateTimeField(auto_now_add=True, db_column='tmCreatedDate')),
                ('teamUpdatedDate', models.DateTimeField(auto_now=True, db_column='tmUpdatedDate')),
                ('teamIsActive', models.BooleanField(blank=True, db_column='tmIsActive', null=True)),
            ],
            options={
                'db_table': 'tblteam',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('tkaidpk', models.AutoField(db_column='tkaIdpk', primary_key=True, serialize=False)),
                ('tkaAssigner', models.IntegerField(blank=True, db_column='tkaAssignerUserIdfk', null=True)),
                ('tkaRemarks', models.CharField(blank=True, db_column='tkaRemarks', max_length=255, null=True)),
                ('tkaCreateDdate', models.DateTimeField(auto_now_add=True, db_column='tkaCreatedDate')),
                ('tkaUpdateddate', models.DateTimeField(auto_now=True, db_column='tkaUpdatedDate')),
                ('tkaiIsActive', models.BooleanField(blank=True, db_column='tkaIsActive', default=True)),
                ('tkaAssignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tkaTask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task.task')),
            ],
            options={
                'db_table': 'tbltaskassignment',
                'managed': True,
            },
        ),
    ]
